// AUTO-GENERATED by tools/gen_real_scenes.py — do not edit by hand.
// Real 시나리오 scenes from the precomputed server-room twin :
//   random_v1 = racks where the scan found them; rl_ppo_v1 = the imitation layout policy's proposal.
// Both are 12/12 ASHRAE-compliant — on this already-tidy room the two layouts look alike, which is the
// truthful result. The dashboard runs the same /optimize live; this bakes it for the side-by-side page.
import type { SceneGraph } from "./sceneGraphs";

export const realRandomPlacement: SceneGraph = {
  id: "random_v1",
  name: "스캔 원본 배치",
  description: "실제 스캔으로 복원한 서버실 — 랙이 발견된 그대로의 배치.",
  room: {
    type: "server_room",
    dimensions: [7.5, 2.28, 3.9],
    openings: [
    { type: "door", wall: "south", position: [3.75, 0, 3.9], width: 1.2 },
    { type: "vent", wall: "west", position: [0, 2.0, 3.05], width: 1.4 },
    ],
  },
  furniture: [
  { id: "rack_01", category: "server_rack", label: "서버 랙 1", position: [3.1, 0, 0.95], rotation: [0, 0, 0], size: [0.6, 1.95, 0.9], color: "#37474F", heatOutput: 12, relations: [] },
  { id: "rack_02", category: "server_rack", label: "서버 랙 2", position: [3.7, 0, 0.95], rotation: [0, 0, 0], size: [0.6, 1.95, 0.9], color: "#455A64", heatOutput: 10, relations: [] },
  { id: "rack_03", category: "server_rack", label: "서버 랙 3", position: [4.3, 0, 0.95], rotation: [0, 0, 0], size: [0.6, 1.95, 0.9], color: "#37474F", heatOutput: 6, relations: [] },
  { id: "rack_04", category: "server_rack", label: "서버 랙 4", position: [4.9, 0, 0.95], rotation: [0, 0, 0], size: [0.6, 1.95, 0.9], color: "#455A64", heatOutput: 8, relations: [] },
  { id: "rack_05", category: "server_rack", label: "서버 랙 5", position: [5.5, 0, 0.95], rotation: [0, 0, 0], size: [0.6, 1.95, 0.9], color: "#37474F", heatOutput: 5, relations: [] },
  { id: "rack_06", category: "server_rack", label: "서버 랙 6", position: [6.1, 0, 0.95], rotation: [0, 0, 0], size: [0.6, 1.95, 0.9], color: "#455A64", heatOutput: 7, relations: [] },
  { id: "rack_07", category: "server_rack", label: "서버 랙 7", position: [3.7, 0, 2.95], rotation: [0, 180, 0], size: [0.6, 1.95, 0.9], color: "#37474F", heatOutput: 11, relations: [] },
  { id: "rack_08", category: "server_rack", label: "서버 랙 8", position: [4.3, 0, 2.95], rotation: [0, 180, 0], size: [0.6, 1.95, 0.9], color: "#455A64", heatOutput: 6, relations: [] },
  { id: "rack_09", category: "server_rack", label: "서버 랙 9", position: [4.9, 0, 2.95], rotation: [0, 180, 0], size: [0.6, 1.95, 0.9], color: "#37474F", heatOutput: 9, relations: [] },
  { id: "rack_10", category: "server_rack", label: "서버 랙 10", position: [5.5, 0, 2.95], rotation: [0, 180, 0], size: [0.6, 1.95, 0.9], color: "#455A64", heatOutput: 5, relations: [] },
  { id: "rack_11", category: "server_rack", label: "서버 랙 11", position: [6.1, 0, 2.95], rotation: [0, 180, 0], size: [0.6, 1.95, 0.9], color: "#37474F", heatOutput: 8, relations: [] },
  { id: "rack_12", category: "server_rack", label: "서버 랙 12", position: [6.7, 0, 2.95], rotation: [0, 180, 0], size: [0.6, 1.95, 0.9], color: "#455A64", heatOutput: 6, relations: [] },
  { id: "cooling_01", category: "cooling_unit", label: "스탠드 에어컨 (스캔)", position: [0.25, 0, 3.05], rotation: [0, 90, 0], size: [1.5, 2.0, 0.5], color: "#eae7df", heatOutput: 0, relations: [] },
  { id: "core_switch", category: "network_switch", label: "네트워크 랙 (스캔)", position: [6.7, 0, 0.9], rotation: [0, 0, 0], size: [0.6, 2.0, 0.8], color: "#1565C0", heatOutput: 3, relations: [] },
  { id: "power_cabinet_01", category: "power_cabinet", label: "분전반 (스캔)", position: [1.45, 0, 0.2], rotation: [0, 0, 0], size: [0.7, 2.0, 0.4], color: "#8a978f", heatOutput: 0, relations: [] },
  ],
  score: { total: 0.86, thermal: 0.83, cooling: 0.82, cable: 0.91, proximity: 0.84, constraint: 0.96 },
};

export const realOptimizedPlacement: SceneGraph = {
  id: "rl_ppo_v1",
  name: "RL 최적화 배치 (PPO)",
  description: "imitation 학습 정책이 스캔된 방에 제안한 정렬 배치 — 서버 랙을 정돈된 hot/cold-aisle 행으로 정리.",
  room: {
    type: "server_room",
    dimensions: [7.5, 2.28, 3.9],
    openings: [
    { type: "door", wall: "south", position: [3.75, 0, 3.9], width: 1.2 },
    { type: "vent", wall: "west", position: [0, 2.0, 3.05], width: 1.4 },
    ],
  },
  furniture: [
  { id: "rack_01", category: "server_rack", label: "서버 랙 1", position: [3.2, 0, 0.95], rotation: [0, 0, 0], size: [0.6, 1.95, 0.9], color: "#37474F", heatOutput: 12, relations: [] },
  { id: "rack_02", category: "server_rack", label: "서버 랙 2", position: [3.2, 0, 2.85], rotation: [0, 180, 0], size: [0.6, 1.95, 0.9], color: "#455A64", heatOutput: 10, relations: [] },
  { id: "rack_03", category: "server_rack", label: "서버 랙 3", position: [3.8, 0, 0.95], rotation: [0, 0, 0], size: [0.6, 1.95, 0.9], color: "#37474F", heatOutput: 6, relations: [] },
  { id: "rack_04", category: "server_rack", label: "서버 랙 4", position: [3.8, 0, 2.85], rotation: [0, 180, 0], size: [0.6, 1.95, 0.9], color: "#455A64", heatOutput: 8, relations: [] },
  { id: "rack_05", category: "server_rack", label: "서버 랙 5", position: [4.4, 0, 0.95], rotation: [0, 0, 0], size: [0.6, 1.95, 0.9], color: "#37474F", heatOutput: 5, relations: [] },
  { id: "rack_06", category: "server_rack", label: "서버 랙 6", position: [4.4, 0, 2.85], rotation: [0, 180, 0], size: [0.6, 1.95, 0.9], color: "#455A64", heatOutput: 7, relations: [] },
  { id: "rack_07", category: "server_rack", label: "서버 랙 7", position: [5.0, 0, 0.95], rotation: [0, 0, 0], size: [0.6, 1.95, 0.9], color: "#37474F", heatOutput: 11, relations: [] },
  { id: "rack_08", category: "server_rack", label: "서버 랙 8", position: [5.0, 0, 2.85], rotation: [0, 180, 0], size: [0.6, 1.95, 0.9], color: "#455A64", heatOutput: 6, relations: [] },
  { id: "rack_09", category: "server_rack", label: "서버 랙 9", position: [5.6, 0, 0.95], rotation: [0, 0, 0], size: [0.6, 1.95, 0.9], color: "#37474F", heatOutput: 9, relations: [] },
  { id: "rack_10", category: "server_rack", label: "서버 랙 10", position: [5.6, 0, 2.85], rotation: [0, 180, 0], size: [0.6, 1.95, 0.9], color: "#455A64", heatOutput: 5, relations: [] },
  { id: "rack_11", category: "server_rack", label: "서버 랙 11", position: [6.2, 0, 0.95], rotation: [0, 0, 0], size: [0.6, 1.95, 0.9], color: "#37474F", heatOutput: 8, relations: [] },
  { id: "rack_12", category: "server_rack", label: "서버 랙 12", position: [6.2, 0, 2.85], rotation: [0, 180, 0], size: [0.6, 1.95, 0.9], color: "#455A64", heatOutput: 6, relations: [] },
  { id: "cooling_01", category: "cooling_unit", label: "스탠드 에어컨 (스캔)", position: [0.2, 0, 2.0], rotation: [0, 90, 0], size: [1.5, 2.0, 0.5], color: "#eae7df", heatOutput: 0, relations: [] },
  { id: "core_switch", category: "network_switch", label: "네트워크 랙 (스캔)", position: [7.2, 0, 2.0], rotation: [0, 0, 0], size: [0.6, 2.0, 0.8], color: "#1565C0", heatOutput: 3, relations: [] },
  { id: "power_cabinet_01", category: "power_cabinet", label: "분전반 (스캔)", position: [1.45, 0, 0.2], rotation: [0, 0, 0], size: [0.7, 2.0, 0.4], color: "#8a978f", heatOutput: 0, relations: [] },
  ],
  score: { total: 0.86, thermal: 0.83, cooling: 0.82, cable: 0.91, proximity: 0.84, constraint: 0.96 },
};
